[theme]
base = "light"
primaryColor = "#0F2252"
backgroundColor = "#F7F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1F36"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
